language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x

os:
  - linux
  - osx

matrix:
  include:
    - go: tip
      env: ATREUGO_VERSION=v7
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get -u -v github.com/mattn/goveralls

script:
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - GOARCH=386 go build

  - $GOPATH/bin/goveralls -v -service=travis-ci -package github.com/savsgio/atreugo/$ATREUGO_VERSION
